ebay_website = "ebay.fr"
ebay_user = "Nox_Hamlet"

repo_public_url = "https://github.com/Merinorus/ebay-announce-generator"

# Related to announce content
store_name = "ðŸ˜º Nox hamlet's store"
store_slogan = "ðŸ· ðŸ¥– ðŸ§€  French seller, slow shipping! :>"